spring:
  application:
    name: hi-gateway-service
server:
  port: 5000
eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    auth:
      path: /uaa/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: hi-auth-service
    user:
      path: /user/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: hi-user-service
security:
  basic:
    enabled: false
  oauth2:
#    sso:
#      loginPath: /login
    client:
      ##网关的地址
      access-token-uri: http://localhost:9050/uaa/oauth/token
#      user-authorization-uri: http://localhost:9030/user/oauth/authorize
      client-id: webApp
      client-secret: webApp
    resource:
      user-info-uri:  http://localhost:9060/user
      prefer-token-info: false
#security:
#  oauth2:
#    resource:
#      id: gateway
#      user-info-uri: http://localhost:9060/user
#      prefer-token-info: false
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
###超时配置###
