server:
  port: 9010
spring:
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    host: 120.78.170.123
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /

foo: foo version 1